// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx1ijgyRfPEAZRZsvCT8hFK4J0HCnVOE0',
    appId: '1:496725802179:android:3fe4e10af486472bcef676',
    messagingSenderId: '496725802179',
    projectId: 'mychatapp-91295',
    databaseURL: 'https://mychatapp-91295.firebaseio.com',
    storageBucket: 'mychatapp-91295.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMGh_6yEtuHeFY5jqSWjOd4jUPLZ5pm8Y',
    appId: '1:496725802179:ios:cb91a6093e9594bccef676',
    messagingSenderId: '496725802179',
    projectId: 'mychatapp-91295',
    databaseURL: 'https://mychatapp-91295.firebaseio.com',
    storageBucket: 'mychatapp-91295.appspot.com',
    androidClientId: '496725802179-7kmhq0ocv7a67nubfteku9ob2f0m3qq2.apps.googleusercontent.com',
    iosClientId: '496725802179-n041pdpfk6u0ecneo68f1siqhm0g7lg8.apps.googleusercontent.com',
    iosBundleId: 'com.quickchat.quickchat',
  );
}
